### ISSUE TITLE
Can't make example in doc work

### ISSUE THREAD

**Issue by hhaawwaa** [wsantos/motorm#5]
I am trying to make the example in the doc work but I am not able to. I am using Python 3.4 and Tornado 4.3. Used code is the following. Many thanks for any help!

import tornado
from motorm import *
from schematics.types import StringType, URLType

class Person(AsyncModel):
    name = StringType(required=True)
    website = URLType()

connect('Test')

@tornado.gen.coroutine
def test():
    person = Person()
    person.name = "Jonny Bravo"
    person.website = "http://google.com"
    yield person.save()

test()

Future <tornado.concurrent.Future object at 0x02EB5AF0> exception was never retrieved: Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\tornado\gen.py", line 282, in wrapper
    yielded = next(result)
  File "D:/Development/pycharm/motorm/main.py", line 16, in test
    yield person.save()
  File "C:\Python34\lib\site-packages\tornado\concurrent.py", line 473, in wrapper
    future.result()
  File "C:\Python34\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Python34\lib\site-packages\tornado\concurrent.py", line 461, in wrapper
    result = f(_args, *_kwargs)
  File "D:\Development\pycharm\motorm\motorm__init__.py", line 190, in save
    if self.id:
AttributeError: 'Person' object has no attribute 'id'

**Comment by wsantos** [comment]
Note that motorm was meant to be used in conjuntion with Tornado, so you should have IOLoop instance running, this code works fine:

``` python
import tornado
from tornado.ioloop import IOLoop
from motorm import *
from schematics.types import StringType, URLType

class Person(AsyncModel):
    name = StringType(required=True)
    website = URLType()

connect('Test')

@tornado.gen.coroutine
def test():
    person = Person()
    person.name = "Jonny Bravo"
    person.website = "http://google.com"
    yield person.save()
    print person.serialize()


if __name__ == '__main__':
    test()
    IOLoop.instance().start()
```

_Ps._: motorm is only compatible with motor <= 0.3

**Comment by hhaawwaa** [comment]
Great! Thanks!
